### ISSUE TITLE
No version of NDK matched the requested version 20.0.5594570. Versions available locally: 21.3.6528147

### ISSUE THREAD

**Issue by DreamPWJ** [mindrunner/docker-android-sdk#65] opened 2020-12-14 02:05 UTC
Execution failed for task ':base:stripDebugDebugSymbols'.

**Comment by mindrunner** [comment] 2020-12-14 09:52
Possibly a duplicate of https://github.com/mindrunner/docker-android-sdk/issues/56

A little bit of more information would be highly appreciated next time you open an issue! :)

**Closed by mindrunner** 2020-12-14 09:52 UTC
