### ISSUE TITLE
Unable to use SDK Manager

### ISSUE THREAD

**Issue by rajand87** [mindrunner/docker-android-sdk#76] opened 2021-08-06 05:09 UTC
gives below error in Ubuntu standalone image.
/opt/android-sdk-linux/tools/bin/sdkmanager
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

**Comment by mindrunner** [comment] 2021-08-07 16:09
Closing as a duplicate of https://github.com/mindrunner/docker-android-sdk/issues/74

**Closed by mindrunner** 2021-08-07 16:09 UTC
