### ISSUE TITLE
Unable to create new analytics settings: /opt/android-sdk-linux/analytics.settings (Permission denied)

### ISSUE THREAD

**Issue by typeless** [mindrunner/docker-android-sdk#39] opened 2019-06-06 10:33 UTC
```
Unable to create new analytics settings: /opt/android-sdk-linux/analytics.settings (Permission denied)
```
Will submit a PR later on when tested ok.

**Comment by mindrunner** [comment] 2019-06-07 02:13
When does that happen?

**Comment by typeless** [comment] 2019-06-09 01:20
@mindrunner When building an Android project using Gradle.
I am on short days off, so not available until next week.
Last time I tried my fix, I encountered some error related to our build infra, which I haven't figured out.
My fix was to add a `chmod 0777 ...` at https://github.com/mindrunner/docker-android-sdk/blob/master/tools/entrypoint.sh#L11. I thought that would work.

**Comment by mindrunner** [comment] 2019-06-10 00:06
Do you use the container as a sidecar or do you build directly with that image?

**Comment by typeless** [comment] 2019-06-10 02:02
@mindrunner I use the image directly.

**Comment by typeless** [comment] 2019-06-10 02:39
I run the container with a non-root user. Otherwise, if I run it with root, it works correctly.

**Comment by mindrunner** [comment] 2019-06-10 02:41
Can you give me the exact command you use for starting the build?

**Comment by typeless** [comment] 2019-06-10 03:04
```
kind: pipeline
name: default

steps:
- name: build
  image: runmymind/docker-android-sdk
  commands:
    - ./make.sh

- name: release
  image: runmymind/docker-android-sdk
  commands:
    - apt-get update && apt-get install -y zip
    - ./release.sh
  depends_on:
    - build
  when:
    event: tag

- name: gitea_release
  debug: true
  image: plugins/gitea-release:latest
  settings:
    insecure: true
    base_url: http://192.120.100.175:3000
    api_key:
        from_secret: gitea_token
    files:
      - PosService/build/outputs/aar/*.zip
    checksum:
      - md5
      - sha256
  depends_on:
    - release
  when:
    event: tag
```
The above is the Drone CI configuration.

The content of `make.sh`:
`./gradlew clean build assembleAndroidTest`

**Comment by typeless** [comment] 2019-06-10 06:39
It turned out `chmod -R 0777 /opt/android-sdk-linux` is the only working solution.

**Comment by typeless** [comment] 2019-06-10 08:09
I gave up running the container with a different user.

**Comment by mindrunner** [comment] 2019-06-10 18:23
Hi
this images is supposed to be used as a user with the UID 1000. There is no real clean solution to enable it for all users. The chmod thing has some drawbacks, this is why I did not put it in.

In your example, I do not see any usage of another user, so I would assume, it should be working. 

Why do you need to run this as another user?

**Comment by typeless** [comment] 2019-06-10 22:58
I intended to use `Drone` CLI as a build-farm controller for containerized builds.
So, we can build our sources using the CI infrastructure without first pushing to the Git hosting server.
Currently, the Drone CLI can run the build pipelines for a local source tree by sharing the host working directory as the container's volume. But the generated binary and other by-products are owned by root. That makes my colleagues who don't have sudo privilege unable to remove those files.

**Comment by typeless** [comment] 2019-06-10 23:05
Another approach I can find is to use `docker cp.`
But it doesn't seem to be usable when the output files are enormous (like more than 10GB).
The particular example we encounter is the builds of Android BSP.
Other smaller projects are probably ok with the way.

**Comment by mindrunner** [comment] 2019-06-10 23:24
> But the generated binary and other by-products are owned by root. 
This should definitely never be the case. Actually, this means (probably), that the build ran as the root user. Can you confirm that? Why do you build as root? 

I do not know Drone. Never used it. I am happy to have a look at your build system, if you would like me to.

**Comment by typeless** [comment] 2019-06-10 23:44
I’m not at my computer but iirc that’s true. And I think that’s due to drone runs the image with the root user argument.

I’ll have a look. Anyway, I appreciate your help 🙏

**Comment by mindrunner** [comment] 2019-06-11 04:12
I fired up a Drone CI build with the latest image and built one of my android apps with it. Indeed, Drone seems to override the default user with root, which I cannot really understand. Also, there seems no way to change that behavior in the build config. 

Still I do not really understand, where this leads to a problem. If the build runs as root, the deployment will probably be root as well. Thus, there should always be permission to the SDK folder by design.

Of course, if the build writes to a mounted volume or directory, those files are also owned by root. You can chown them to whatever you want after the build to make your users being able to delete the files. 

Generally, this looks like a design issue in the whole process (definitely, do not use the root user for the build, for so many reasons). My approach of going around the Drone CI behavior would be to change user back to a non-privileged one (UID: 1000) before doing anything else.

**Comment by mindrunner** [comment] 2019-06-11 04:23
I need to correct my previou

**Comment by mindrunner** [comment] 2020-01-03 22:33
I just saw that I left this open and forgot about it. Is this still an issue for you?

**Comment by mindrunner** [comment] 2020-01-03 22:51
Alright, I checked the git history and it seems that from the beginning, this was running as the root user per default. I remember that I have had reasons for doing this. If you look at https://github.com/mindrunner/docker-android-sdk/blob/master/tools/entrypoint.sh you will see that the SDK update is done as the UID 1000. 

This images were never created to run in another environment than the internal CI/CD system of the company I was working for. Thus, there might be issues with running it on other CIs.

Maybe it is a good idea to re-evaluate this and maybe change the default user to UID 1000 as well. However, this sounds like a big change to me and should be tested thoroughly.

I am not actively working on this at the moment and do not have a lot of time, but I am happy to see, review and merge PRs if there are some!

**Comment by typeless** [comment] 2020-01-04 04:32
@mindrunner No, I don't have the issue anymore. I forgot how I fixed it either :) I do still run the image for my projects. Thanks.

**Comment by mindrunner** [comment] 2020-01-04 06:33
Alright, closing it here until someone thinks that this is an issue :)

**Closed by mindrunner** 2020-01-04 06:33 UTC
Labels: enhancement, help wanted
